In [60]:
import pandas as pd
import scipy.stats
import numpy as np

In [3]:
df = pd.read_csv("gene_high_throughput_sequencing.csv")

In [6]:
df['Diagnosis'].value_counts()

early neoplasia    25
normal             24
cancer             23
Name: Diagnosis, dtype: int64

In [53]:
print(df.shape)
df.head()

(72, 15750)


Patient_id Diagnosis  LOC643837  LOC100130417     SAMD11  \
0  STT5425_Breast_001_normal    normal   1.257614      2.408148  13.368622   
1  STT5427_Breast_023_normal    normal   4.567931     16.602734  42.477752   
2  STT5430_Breast_002_normal    normal   2.077597      3.978294  12.863214   
3  STT5439_Breast_003_normal    normal   2.066576      8.520713  14.466035   
4  STT5441_Breast_004_normal    normal   2.613616      3.434965  12.682222   

       NOC2L     KLHL17    PLEKHN1   C1orf170       HES4  ...      CLIC2  \
0   9.494779  20.880435  12.722017   9.494779  54.349694  ...   4.761250   
1  25.562376  23.221137  11.622386  14.330573  72.445474  ...   6.871902   
2  13.728915  14.543176  14.141907   6.232790  57.011005  ...   7.096343   
3   7.823932   8.520713   2.066576  10.870009  53.292034  ...   5.200770   
4  10.543189  26.688686  12.484822   1.364917  67.140393  ...  11.227770   

     RPS4Y1       ZFY      PRKY     USP9Y     DDX3Y       CD24  CYorf15B  \
0  1.257614  1.257614  1.257614  1.257614  1.257614  23.268694  1.257614   
1  1.815112  1.815112  1.815112  1.815112  1.815112  10.427023  1.815112   
2  2.077597  2.077597  2.077597  2.077597  2.077597  22.344226  2.077597   
3  2.066576  2.066576  2.066576  2.066576  2.066576  49.295538  2.066576   
4  1.364917  1.364917  1.364917  1.364917  1.364917  23.627911  1.364917   

      KDM5D    EIF1AY  
0  1.257614  1.257614  
1  1.815112  1.815112  
2  2.077597  2.077597  
3  2.066576  2.066576  
4  1.364917  1.364917  

[5 rows x 15750 columns]

In [55]:
" ".join(df.columns)

'Patient_id Diagnosis LOC643837 LOC100130417 SAMD11 NOC2L KLHL17 PLEKHN1 C1orf170 HES4 ISG15 AGRN C1orf159 LOC254099 TTLL10 TNFRSF18 TNFRSF4 SDF4 B3GALT6 FAM132A UBE2J2 SCNN1D ACAP3 PUSL1 CPSF3L GLTPD1 DVL1 MXRA8 AURKAIP1 CCNL2 LOC148413 MRPL20 LOC441869 VWA1 ATAD3C ATAD3B ATAD3A C1orf70 SSU72 LOC643988 MIB2 CDK11B SLC35E2B CDK11A SLC35E2 NADK GNB1 CALML6 TMEM52 GABRD PRKCZ C1orf86 SKI MORN1 RER1 PEX10 PLCH2 PANK4 HES5 LOC115110 TNFRSF14 LOC100133445 C1orf93 MMEL1 FLJ42875 PRDM16 ARHGEF16 MEGF6 TPRG1L WRAP73 TP73 TP73-AS1 LOC388588 LRRC47 CEP104 DFFB C1orf174 AJAP1 NPHP4 KCNAB2 CHD5 RPL22 RNF207 ICMT GPR153 ACOT7 HES2 ESPN TNFRSF25 PLEKHG5 NOL9 TAS1R1 ZBTB48 KLHL21 PHF13 THAP3 DNAJC11 CAMTA1 VAMP3 PER3 TNFRSF9 PARK7 ERRFI1 SLC45A1 RERE ENO1 CA6 SLC2A5 H6PD SPSB1 SLC25A33 TMEM201 PIK3CD C1orf200 CLSTN1 CTNNBIP1 LZIC NMNAT1 RBP7 UBE4B KIF1B PGD APITD1 CORT DFFA PEX14 CASZ1 C1orf127 TARDBP MASP2 SRM EXOSC10 MTOR ANGPTL7 UBIAD1 PTCHD2 FBXO2 FBXO44 FBXO6 MAD2L2 AGTRAP MTHFR CLCN6 NPPA KIAA2

In [26]:
X1 = df[df['Diagnosis'] == 'normal'].iloc[:, 2:]
X2 = df[df['Diagnosis'] == 'early neoplasia'].iloc[:, 2:]
X3 = df[df['Diagnosis'] == 'cancer'].iloc[:, 2:]

In [39]:
ans = 0
p_values_1 = []
for i in range(X1.shape[1]):
    p_values_1.append(scipy.stats.ttest_ind(X1.iloc[:, i], X2.iloc[:, i], equal_var=False)[1])
    ans += scipy.stats.ttest_ind(X1.iloc[:, i], X2.iloc[:, i], equal_var=False)[1] < 0.05
with open('1.1.txt', 'w') as file:
    file.write(str(ans))
ans

1575

In [50]:
ans = 0
p_values_2 = []
for i in range(X1.shape[1]):
    p_values_2.append(scipy.stats.ttest_ind(X2.iloc[:, i], X3.iloc[:, i], equal_var=False)[1])
    ans += scipy.stats.ttest_ind(X2.iloc[:, i], X3.iloc[:, i], equal_var=False)[1] < 0.05
with open('1.2.txt', 'w') as file:
    file.write(str(ans))
ans

3490

In [51]:
import statsmodels.stats.multitest as smm

In [77]:
mod1 = smm.multipletests(p_values_1, 
                        alpha = 0.025, 
                        method = 'holm')
mod2 = smm.multipletests(p_values_2, 
                        alpha = 0.025, 
                        method = 'holm')

def fold_change(control, treatment):
    C = control.values.mean(axis=0)
    T = treatment.values.mean(axis=0)
    return np.where(T > C, T / C, -C / T)


ans1 = np.sum(np.abs(fold_change(X1, X2)[mod1[0]]) > 1.5)
with open('2.1.txt', 'w') as file:
    file.write(str(ans1))

ans2 = np.sum(np.abs(fold_change(X2, X3)[mod2[0]]) > 1.5)    
with open('2.2.txt', 'w') as file:
    file.write(str(ans2))
    
ans1, ans2

(2, 77)

In [78]:
mod1 = smm.multipletests(p_values_1, 
                        alpha = 0.025, 
                        method = 'fdr_bh')
mod2 = smm.multipletests(p_values_2, 
                        alpha = 0.025, 
                        method = 'fdr_bh')

def fold_change(control, treatment):
    C = control.values.mean(axis=0)
    T = treatment.values.mean(axis=0)
    return np.where(T > C, T / C, -C / T)


ans1 = np.sum(np.abs(fold_change(X1, X2)[mod1[0]]) > 1.5)
with open('3.1.txt', 'w') as file:
    file.write(str(ans1))

ans2 = np.sum(np.abs(fold_change(X2, X3)[mod2[0]]) > 1.5)    
with open('3.2.txt', 'w') as file:
    file.write(str(ans2))
    
ans1, ans2

(4, 524)

In [63]:
fold_change(X1, X2)[mod1[0]]

array([1.50978548, 1.97486767])

In [45]:
mod1

(array([False, False, False, ..., False, False, False]),
 array([1.        , 0.50017368, 1.        , ..., 1.        , 1.        ,
        1.        ]),
 3.2571254033886277e-06,
 3.1750063500127e-06)

In [73]:
np.mean([[1, 10],[1, 10]], axis=0)

array([ 1., 10.])