In [148]:
import pandas as pd
import numpy as np
from sklearn.cluster import MeanShift

In [149]:
df = pd.read_table('checkins.dat', sep='|', skipinitialspace = True, header=[0], skiprows=[1],)
df = df.dropna(axis='rows').reset_index(drop=True)

/home/pavel/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [150]:
df.head()

id       user_id   venue_id   latitude        longitude       \
0  984222    15824.0     5222.0       38.895112      -77.036366   
1  984234    44652.0     5222.0       33.800745      -84.410520   
2  984291   105054.0     5222.0       45.523452     -122.676207   
3  984318  2146539.0     5222.0       40.764462     -111.904565   
4  984232    93870.0   380645.0       33.448377     -112.074037   

      created_at        
0  2012-04-21 17:43:47  
1  2012-04-21 17:43:43  
2  2012-04-21 17:39:22  
3  2012-04-21 17:35:46  
4  2012-04-21 17:38:18

In [151]:
df.columns = map(lambda x: x.strip(), df.columns)
df.columns

Index(['id', 'user_id', 'venue_id', 'latitude', 'longitude', 'created_at'], dtype='object')

In [94]:
#обучаем алгоритм
ms = MeanShift(bandwidth=0.1)
ms.fit(df[['latitude', 'longitude']].iloc[:100000,])

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=1,
     n_jobs=None, seeds=None)

In [95]:
labels = ms.labels_
cluster_centers = ms.cluster_centers_

In [152]:
#делаем датасет с лейблами, чтобы отобрать кластеры с более чем 15 точками
labeled_df = pd.concat([df[['latitude', 'longitude']].iloc[:100000,], pd.DataFrame(labels, columns=['label'])], axis = 1)
big_clusters = labels_unique[labeled_df.groupby(['label']).count().iloc[:,0] > 15]

In [156]:
clusters = np.array(cluster_centers[big_clusters])
clusters[:10]

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       [  41.87824378,  -87.62984336],
       [  37.68868157, -122.40933037],
       [  38.88616522,  -77.04878333],
       [  33.35734456, -111.82265411],
       [  33.76663623,  -84.39328918],
       [  42.36321864,  -71.07368761],
       [  47.60624472, -122.33204383]])

In [154]:
offices =  np.array([[33.751277, -118.188740],
                     [25.867736, -80.324116],
                     [51.503016, -0.075479],
                     [52.378894, 4.885084],
                     [39.366487, 117.036146],
                     [-33.868457, 151.205134]])

In [155]:
#находим ближайшие к офисам центры кластеров
sorted(clusters, key = lambda x: np.min(np.linalg.norm(x - offices, axis=1)))[:20]

[array([-33.86063043, 151.20477593]),
 array([52.37296399,  4.89231722]),
 array([ 25.84567226, -80.3188906 ]),
 array([51.50299126, -0.12553729]),
 array([  33.80987796, -118.14892381]),
 array([ 25.78581242, -80.21793804]),
 array([ 25.70534972, -80.28342874]),
 array([ 26.01009825, -80.19999059]),
 array([  33.88832534, -118.04892817]),
 array([  33.87298601, -118.36209115]),
 array([  33.97257482, -118.16837067]),
 array([ 26.13884379, -80.33434684]),
 array([  33.98393587, -118.00740497]),
 array([ 26.12086266, -80.15890668]),
 array([  33.81730643, -117.89124917]),
 array([  34.06039755, -118.24870903]),
 array([  33.67430266, -117.85878927]),
 array([ 26.20058464, -80.25071613]),
 array([  34.03548695, -118.43899772]),
 array([  34.13146015, -118.11801181])]